#+title: Log

* <2024-02-02 Fri>

** Scheduling

Aujourd'hui c'est de l'animation de sprites. Je vais le faire sur ma tablette.
Je devrai aller au Starbucks pour bosser, c'est un travail qui peut etre nomade.

*** PROJ Animation Idle :ASSET:
*** PROJ Animation Course :ASSET:
*** PROJ Animation Saut :ASSET:
*** PROJ Animation Double-Saut :ASSET:
*** PROJ Animation Mort :ASSET:
*** PROJ Implementation Animation :PROG:
*** PROJ Anim dynamique :PROG:

** Bilan de la journée

Je suis bloqué sur l'animation, objectifs non-accomplis. Je vais faire ca
plus tard je pense.

* <2024-02-03 Sat>

** Scheduling

On essaye de reprendre le process d'animation, mais sur PC cette fois. Animation
procédurale des projectiles.

*** DONE Transformations/modifications dynamiques :PROG:
*** DONE Réaction saut au-dessus a l'atterrissage :PROG:
*** DONE Pulsation :PROG:
*** DONE Destruction (particules ?) :PROG:

** Bilan de la journée

J'ai bien avancé sur l'animation procédurale. J'ai découvert les AnimationTree,
très pratique pour orchestrer des AnimationPlayer et des animations.
Le jeu commence à être relativement juicy. Il manque peut-être quelques
particules/gfx, et bien sur des sfx.
